### ISSUE TITLE
go get import issues

### ISSUE THREAD

**Issue by debarshri** [kch42/golibrsync#3]
```
# github.com/silvasur/golibrsync/librsync
/Users/dbasak/src/github.com/silvasur/golibrsync/librsync/librsync.go:7:10: fatal error: 'librsync.h' file not found
#include <librsync.h>
         ^
1 error generated.
```

**Comment by silvasur** [comment]
Hmm, works for me. Check, if you have the librsync library installed on your system. It looks like you have a macOS system? I don't own a mac, so unfortunately I can't help you too much, but perhaps [this page](http://rudix.org/packages/librsync.html) can help you? And I think macOS has a package manager called Homebrew? Perhaps you can find something there.

**Comment by silvasur** [comment]
Is the build still failing for you? If no, I would like to close the issue. But if it still does, please post some more info about your system. Which Go version and which OS are you using for a start. Perhaps I can help if I have more info.

**Comment by silvasur** [comment]
I'm closing this issue now. Feel free to reopen it or file a new issue if the build is still failing for you.
